"""fazendo diferenciação entre users admins de diferentes empresas

Revision ID: 6658f4a46d0e
Revises: d7b24c2a758b
Create Date: 2025-11-23 03:33:18.128844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6658f4a46d0e'
down_revision: Union[str, None] = 'd7b24c2a758b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros', 'tipo',
               existing_type=postgresql.ENUM('Entrada', 'Saída', name='tipo_registro'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('users', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint('uq_user_empresa', 'users', ['empresa_id', 'username'])
    op.create_foreign_key(None, 'users', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_user_empresa', 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'empresa_id')
    op.alter_column('registros', 'tipo',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Entrada', 'Saída', name='tipo_registro'),
               existing_nullable=False)
    # ### end Alembic commands ###
