"""fix: permite que o id de empresa na tabela users seja nulo

Revision ID: 98207ad9d253
Revises: fc9988963ec6
Create Date: 2025-11-23 17:41:01.038854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98207ad9d253'
down_revision: Union[str, None] = 'fc9988963ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
