"""altera a tabela de funcionarios

Revision ID: ab4eddb4749f
Revises: 98207ad9d253
Create Date: 2025-12-22 22:21:58.149248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4eddb4749f'
down_revision: Union[str, None] = '98207ad9d253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('funcionarios_pis_key', 'funcionarios', type_='unique')
    op.drop_column('funcionarios', 'pis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('pis', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('funcionarios_pis_key', 'funcionarios', ['pis'])
    # ### end Alembic commands ###
